#!/usr/bin/env bash

choice=$(echo -e "browser\nemacs\nspotify\nfile-manager\nmonitors\naudio\nfont-manager\nbooks" | dmenu)

case "$choice" in
  browser) firefox & ;;
  emacs) emacs & ;;
  spotify) spotify & ;;
  file-manager) dolphin & ;;
  monitors) arandr & ;;
  audio) pavucontrol & ;;
  font-manager) font-manager & ;;
  books) calibre & ;;
esac
