#!/usr/bin/env bash

choice=$(echo -e "browser\nemacs\nspotify\nfilemanager\nmonitors\naudio" | dmenu)

case "$choice" in
  browser) firefox & ;;
  emacs) emacs & ;;
  spotify) spotify & ;;
  filemanager) dolphin & ;;
  monitors) arandr & ;;
  audio) pavucontrol & ;;
esac
