#!/usr/bin/env bash

choice=$(echo -e "browser\nemacs\nspotify\nfile-manager\nmonitors\naudio\nfont-manager\nzoom\ncalibre\nanki\ntorrent\nidea\nbluetooth\nnitrogen" | dmenu)

case "$choice" in
  browser) firefox & ;;
  emacs) emacs & ;;
  spotify) spotify & ;;
  file-manager) dolphin & ;;
  monitors) arandr & ;;
  audio) pavucontrol & ;;
  font-manager) font-manager & ;;
  zoom) zoom & ;;
  calibre) calibre & ;;
  anki) anki & ;;
  torrent) qbittorrent & ;;
  idea) idea-community & ;;
  bluetooth) blueman-manager & ;;
  nitrogen) nitrogen & ;;
esac
